package com.example.cropMonitorSystem.dto.impl;

import com.example.cropMonitorSystem.dto.SuperDTO;
import com.example.cropMonitorSystem.dto.UserStatus;
import com.example.cropMonitorSystem.entity.Role;
import jakarta.persistence.Id;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
public class UserDTO implements SuperDTO, UserStatus {
    @Null(message = "Code generated by server")
    private String user_id;
    @NotNull
    @Email
    private String email;
    @NotNull
    private String password;
    @NotNull
    private Role role;
}
